spring:
  application:
    name: MedicalChat-de
  data:
    redis:
      host: localhost
      port: 6379
#  datasource:
#    driverClassName:
#    url:
#    username:
#    password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    path: ./logs/MedicalChat/